appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: nQfnEeH+ugCb9WQhge2JPl8gXC6uB/iyFq1dv+MFTyDRDAXyCqa+MAwTjA7Rqt+ANbMQY805CRETTGw599ZWNW0pwDi10eTPISCaPivP25s5Dzf4WNUJ30DqTrOi4Uxz61JBUa1JmAhQ/eYTarkOADtuBjuGqwyukES8lJFyMxWMqK2yakoycBo33/43sqiaJ9Dombs8TtLGBST7cyqOFQMIiWxuT/gPqzPQTG3SproVcxmowMtlcp1fJRvLz0xwiiRz2/K4zG4WBIK0nsAI9NqlQdDSuZtPYPsGMZe6R6s3LSO7HaAVUYwF++HVf60gQ5DpLaOgDtb85Hr+0X4bG5s3oEXA7Tu0SqJq6+nvIf734RaAgG0EYfsjammR/ryNdslD/ItAhfEKuErdovihwYKdU7jB3xpwlWh+KnmVhKnjrkZdAwwkZIizj9XVtgenPUS4yQzQdVuFXfp2Qo1bNcvpmQk1pG0pCvdz3M+/+JT1to/sXWFw8wq7zqOWKlvzKXwVsP0u4vMlZY6OdUKuMoOOe0E0EIEKoQBm0UsMPC7hH/5S07/GnNDCcee8/Ie7k91PfT0h3k0/8q1PaBbgtiiMXYVJaeKblhi+RsUdASSX9mSWux9b4iAdQHbERDNbC6s6tvu0k/PaWbPr9Fzi/MRmTSp1Nb7Ab2GfEcRIinc=}
bot:
  automerge: true
